apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-appset
spec:
  generators:
    - git:
        repoURL: "https://github.com/AlonElimelech/final-targil.git"
        revision: HEAD  # You can use a branch, tag, or commit SHA
        directories:
          - path: "definition-infra-tools/*"  # Path pattern where ArgoCD will look for subdirectories
  template:
    metadata:
      name: "{{path.basename}}"  # Dynamically name each application based on the directory name
    spec:
      project: default  # You can specify a project if you have ArgoCD Projects
      source:
        repoURL: "https://github.com/AlonElimelech/final-targil.git"
        targetRevision: "{{revision}}"  # You can use a dynamic revision (e.g., branch)
        path: "{{path}}"  # Dynamically set the path to the subdirectory in the Git repo
      destination:
        server: "https://kubernetes.default.svc"  # Default Kubernetes cluster
        namespace: "{{path.basename}}"  # Dynamically set the namespace to the directory name
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
