apiVersion: v2
name: my-argocd
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
- name: argo-cd
  version: 7.6.12
  repository: https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd