apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appsets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AlonElimelech/final-targil.git
    targetRevision: HEAD
    path: 'entire-solution/appsets/infra-appset.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
