apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-appset
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/AlonElimelech/final-targil.git
        revision: HEAD  # You can use a branch, tag, or commit SHA
        files:
          - path: "entire-solution/metadata-infra-tools/*/values.json"  # Path pattern where ArgoCD will look for subdirectories
  template:
    metadata:
      name: '{{.folder}}'  # Dynamically name each application based on the directory name
    spec:
      project: default  # You can specify a project if you have ArgoCD Projects
      source:
        repoURL: https://github.com/AlonElimelech/final-targil.git
        targetRevision: HEAD  # You can use a dynamic revision (e.g., branch)
        path: 'entire-solution/definition-infra-tools/{{.folder}}'  # Dynamically set the path to the subdirectory in the Git repo
      destination:
        server: "https://kubernetes.default.svc"  # Default Kubernetes cluster
        namespace: '{{.namespace}}'  # Dynamically set the namespace to the directory name
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
      createNamespace: true  # Create the namespace if it doesn't exist
    # maybe we need to add server side 
