apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: {{ .Release.Name }}
  namespace: {{ include "chart.namespaceName" . }}
  labels:
    dashboards: "grafana"
spec:
  service:
    spec:
      type: {{ .Values.service.type }}
  config:
    log:
      mode: "console"
    security:
      admin_user: {{ .Values.auth.adminUser }}
      admin_password: {{ .Values.auth.adminPassword }}
    auth:
      disable_login_form: "false"
