annotations:
  category: My Prometheus Operator
appVersion: 1.0.0
apiVersion: v1
description: A Warpper of Helm chart Kube Prometheus Stack Operator
name: my-prometheus-operator
version: 1.0.0
kubeVersion: ">=1.21.0-0"
dependencies:
- name: kube-prometheus-stack
  version: 69.5.1
  repository: https://prometheus-community.github.io/helm-charts