# grafana
grafana:
  enabled: false
  labelForReloader: grafana_dashboard

kube-prometheus-stack:
  prometheus:
    service:
      type: NodePort
  grafana:
    enabled: false
  prometheus-node-exporter:
    hostRootFsMount:
      enabled: false
